services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: owp_sakthi
      POSTGRES_USER: owp_user
      POSTGRES_PASSWORD: owp_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - media_data:/app/media
      - static_data:/app/staticfiles

volumes:
  postgres_data:
  media_data:
  static_data: