# Generated by Django 5.2.16 on 2026-07-26 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_productspecgroup_productspeccolumn_productspecrow_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildwoodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("outdoor", "Outdoor"), ("indoor", "Indoor")],
                        max_length=20,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Childwood categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ChildwoodGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="cms.childwoodcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PlayEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="childwood/")),
                (
                    "dimensions",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cms.childwoodgroup",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Play equipment",
                "ordering": ["sort_order", "sku"],
            },
        ),
    ]
