# Generated by Django 5.2.16 on 2026-07-26 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0004_childwoodcategory_childwoodgroup_playequipment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("image", models.ImageField(blank=True, upload_to="case-studies/")),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_studies",
                        to="cms.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Case studies",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
