# Generated by Django 5.2.16 on 2026-07-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0005_casestudy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Digital Signage, LCD Panels",
                        max_length=100,
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="partners/")),
                ("website", models.URLField(blank=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
