# Generated by Django 5.2.16 on 2026-07-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0006_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("tagline", models.CharField(blank=True, max_length=300)),
                ("logo", models.ImageField(blank=True, upload_to="settings/")),
                ("favicon", models.ImageField(blank=True, upload_to="settings/")),
                ("phone_primary", models.CharField(blank=True, max_length=20)),
                ("phone_secondary", models.CharField(blank=True, max_length=20)),
                ("email_primary", models.EmailField(blank=True, max_length=254)),
                ("email_support", models.EmailField(blank=True, max_length=254)),
                ("address_line1", models.CharField(blank=True, max_length=300)),
                ("address_line2", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("google_maps_embed", models.TextField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                ("about_content", models.TextField(blank=True)),
                ("mission", models.TextField(blank=True)),
                ("vision", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Company Information",
                "verbose_name_plural": "Company Information",
            },
        ),
        migrations.DeleteModel(
            name="SiteSettings",
        ),
    ]
