# Generated by Django 5.2.16 on 2026-07-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0007_companyinfo_delete_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="hero_description",
            field=models.TextField(
                blank=True,
                default="Complete end-to-end technology partner for restaurants, hotels, retail outlets, and corporate spaces. High-performance hardware, customized digital displays, and 24/7 on-ground support.",
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="hero_title",
            field=models.CharField(
                blank=True,
                default="Digital Signage, Kiosks & IT Solutions",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="trust_chips",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
