# Generated by Django 5.2.16 on 2026-07-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0008_companyinfo_hero_description_companyinfo_hero_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinfo",
            name="hero_description",
            field=models.TextField(
                blank=True,
                default="Sakthi Solutions is your trusted end-to-end technology partner, delivering international-grade digital signage, interactive kiosks, and customer feedback solutions.\nWe specialize in high-performance hardware, customized commercial displays, structured IT networking consulting, and seamless system integrations.\nOur products are designed to help restaurants, hotels, hospitals, retail showrooms, and corporate workspaces operate with absolute efficiency.\nFrom initial site surveys and system design to professional installation, we provide a complete 24/7 on-ground maintenance support framework.\nSince 2014, our Chennai-based expert team has been committed to prompt services and reliable partnerships, ensuring your business stays ahead.",
            ),
        ),
    ]
