# Generated by Django 5.2.16 on 2026-07-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0009_alter_companyinfo_hero_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinfo",
            name="hero_description",
            field=models.TextField(
                blank=True,
                default="Complete end-to-end technology partner for restaurants, hotels, retail outlets, and corporate spaces. High-performance hardware, customized digital displays, and 24/7 on-ground support.",
            ),
        ),
    ]
