# Generated by Django 5.2.16 on 2026-07-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0010_alter_companyinfo_hero_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinfo",
            name="hero_description",
            field=models.TextField(
                blank=True,
                default="We help retail & hospitality brands boost customer engagement and streamline operations with premium digital signage, interactive kiosks, and 24/7 on-ground IT support.",
            ),
        ),
    ]
