# Generated by Django 5.2.16 on 2026-07-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0011_alter_companyinfo_hero_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="hero_bg_image",
            field=models.URLField(
                blank=True,
                default="https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1920&q=80",
                max_length=500,
            ),
        ),
    ]
