# Generated by Django 4.2.16 on 2026-07-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0012_companyinfo_hero_bg_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="advantages",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
