# Generated by Django 4.2.16 on 2026-07-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0013_companyinfo_advantages"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="tagline",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
