# Generated by Django 5.2.16 on 2026-07-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0014_productcategory_tagline"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=200)),
                ("brief", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, upload_to="team/")),
                ("sort_order", models.IntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="brand_color",
            field=models.CharField(
                blank=True, help_text="Hex color e.g. #C8922A", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="business_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="callback_time",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
