# Generated by Django 4.2.16 on 2026-07-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0015_teammember_client_brand_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="about_body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="about_heading",
            field=models.CharField(
                blank=True,
                default="Your Reliable Technology Partner Since 2014",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="about_image",
            field=models.URLField(
                blank=True,
                default="https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=800&q=80",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="cta_subtitle",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="cta_title",
            field=models.CharField(
                blank=True, default="Ready to Transform Your Business?", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="hero_tagline",
            field=models.CharField(
                blank=True,
                default="Since 2014 — Chennai • Hospitality & Retail IT Partner",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="stats",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Trust strip stats: [{value, label}]",
            ),
        ),
    ]
