# Generated by Django 4.2.16 on 2026-07-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0016_companyinfo_about_body_companyinfo_about_heading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="callback_slots",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Contact form callback slots: [{label, value}]",
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="enquiry_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Contact form enquiry types: [{name, sort_order}]",
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="timeline",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="About page timeline: [{year, title, description}]",
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="why_items",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="About page Why Us items: [{icon, title, description}]",
            ),
        ),
    ]
