# Generated by Django 4.2.16 on 2026-07-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0017_companyinfo_callback_slots_companyinfo_enquiry_types_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("tagline", models.CharField(blank=True, max_length=300)),
                ("logo", models.ImageField(blank=True, upload_to="brands/")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Lucide icon name e.g. Monitor, Baby, Users",
                        max_length=50,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="productcategory",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="cms.brand",
            ),
        ),
    ]
