# Generated by Django 4.2.16 on 2026-07-27 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0019_product_dimensions_product_sku_productgroup_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="childwoodgroup",
            name="category",
        ),
        migrations.RemoveField(
            model_name="playequipment",
            name="group",
        ),
        migrations.DeleteModel(
            name="ChildwoodCategory",
        ),
        migrations.DeleteModel(
            name="ChildwoodGroup",
        ),
        migrations.DeleteModel(
            name="PlayEquipment",
        ),
    ]
