# Generated by Django 4.2.16 on 2026-07-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0020_remove_childwoodgroup_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="business_hours",
            field=models.CharField(
                blank=True, default="Mon – Sat: 9:00 AM – 6:30 PM", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="phone_jayakumar",
            field=models.CharField(
                blank=True, help_text="Jayakumar's direct line", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="phone_vidya",
            field=models.CharField(
                blank=True, help_text="Vidya Rani's direct line", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="why_us_bullets",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Contact page 'Why Us' bullet points",
            ),
        ),
    ]
