# Generated by Django 4.2.16 on 2026-07-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0021_companyinfo_business_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="contact_section_heading",
            field=models.CharField(
                blank=True, default="Visit or Call Us", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="contact_section_title",
            field=models.CharField(blank=True, default="Contact Us", max_length=300),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="cta_subtitle_title",
            field=models.CharField(
                blank=True, default="Request a Consultation", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="about_image",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
