# Generated by Django 4.2.16 on 2026-07-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0022_companyinfo_contact_section_heading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="clients_section_title",
            field=models.CharField(blank=True, default="Our Clients", max_length=300),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="products_section_title",
            field=models.CharField(blank=True, default="Our Products", max_length=300),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="testimonials_section_title",
            field=models.CharField(blank=True, default="Testimonials", max_length=300),
        ),
    ]
