# Generated by Django 4.2.16 on 2026-07-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0023_companyinfo_clients_section_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="is_displayed_homepage",
            field=models.BooleanField(
                default=True, help_text="Toggle visibility on homepage product carousel"
            ),
        ),
    ]
