# Generated by Django 4.2.16 on 2026-07-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0024_productcategory_is_displayed_homepage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="is_displayed_homepage",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="is_published",
        ),
        migrations.AddField(
            model_name="brand",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active (Yes/No)"),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active (Yes/No)"),
        ),
    ]
