# Generated by Django 4.2.16 on 2026-07-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0025_remove_brand_is_published_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="is_published",
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active (Yes/No)"),
        ),
        migrations.AddField(
            model_name="solution",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active (Yes/No)"),
        ),
    ]
