# Generated by Django 4.2.16 on 2026-07-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0026_remove_product_is_published_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="client",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="download",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="industry",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="page",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="service",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="is_published",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active (Yes/No)"),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active (Yes/No)"),
        ),
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active (Yes/No)"),
        ),
        migrations.AddField(
            model_name="download",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active (Yes/No)"),
        ),
        migrations.AddField(
            model_name="gallery",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active (Yes/No)"),
        ),
        migrations.AddField(
            model_name="industry",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active (Yes/No)"),
        ),
        migrations.AddField(
            model_name="page",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active (Yes/No)"),
        ),
        migrations.AddField(
            model_name="partner",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active (Yes/No)"),
        ),
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active (Yes/No)"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active (Yes/No)"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active (Yes/No)"),
        ),
    ]
