# Generated by Django 4.2.16 on 2026-07-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0027_remove_blogpost_is_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="show_brand_logo",
            field=models.BooleanField(
                default=True, verbose_name="Show Brand Logo on Category"
            ),
        ),
    ]
