# Generated by Django 4.2.16 on 2026-07-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0029_heroimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="hero_eyebrow",
            field=models.CharField(blank=True, default="Since 2014", max_length=200),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="hero_tagline_subtitle",
            field=models.CharField(
                blank=True,
                default="Chennai • Hospitality & Retail IT Partner",
                max_length=300,
            ),
        ),
    ]
