export const CHILDWOOD_CATALOG = {
  outdoor: [
    { title: "Playstations", items: [
      { sku: "CWP001", image: "/assets/products/about_images.jpg", dimensions: "16*11*12 FT" },
      { sku: "CWP002", image: "/assets/products/about_images.jpg", dimensions: "15*8*12 FT" },
      { sku: "CWP003", image: "/assets/products/about_images.jpg", dimensions: "18*17*12 FT" },
      { sku: "CWP004", image: "/assets/products/about_images.jpg", dimensions: "17*10*13 FT" },
      { sku: "CWP005", image: "/assets/products/about_images.jpg", dimensions: "14*13*11 FT" },
      { sku: "CWP006", image: "/assets/products/about_images.jpg", dimensions: "17*3*10 FT" },
      { sku: "CWP007", image: "/assets/products/about_images.jpg", dimensions: "23*11*11 FT" },
      { sku: "CWP008", image: "/assets/products/about_images.jpg", dimensions: "20*14*11 FT" },
      { sku: "CWP009", image: "/assets/products/about_images.jpg", dimensions: "19*15*12 FT" },
      { sku: "CWP010", image: "/assets/products/about_images.jpg", dimensions: "21*14*11 FT" },
      { sku: "CWP011", image: "/assets/products/about_images.jpg", dimensions: "119*17*11 FT" },
      { sku: "CWP012", image: "/assets/products/about_images.jpg", dimensions: "18*17*12 FT" },
      { sku: "CWP013", image: "/assets/products/about_images.jpg", dimensions: "19*17*11 FT" },
      { sku: "CWP014", image: "/assets/products/about_images.jpg", dimensions: "18*15*10 FT" },
      { sku: "CWP015", image: "/assets/products/about_images.jpg", dimensions: "22*19*14 FT" },
      { sku: "CWP016", image: "/assets/products/about_images.jpg", dimensions: "17*16*14 FT" },
      { sku: "CWP017", image: "/assets/products/about_images.jpg", dimensions: "40*17*27 FT" },
      { sku: "CWP018", image: "/assets/products/about_images.jpg", dimensions: "23*15*12 FT" },
      { sku: "CWP019", image: "/assets/products/about_images.jpg", dimensions: "26*18*12 FT" },
      { sku: "CWP020", image: "/assets/products/about_images.jpg", dimensions: "27*16*12 FT" },
      { sku: "CWP021", image: "/assets/products/about_images.jpg", dimensions: "23*18*11 FT" },
      { sku: "CWP022", image: "/assets/products/about_images.jpg", dimensions: "21*14*13 FT" },
      { sku: "CWP023", image: "/assets/products/about_images.jpg", dimensions: "23*22*11 FT" },
      { sku: "CWP024", image: "/assets/products/about_images.jpg", dimensions: "21*18*8 FT" },
      { sku: "CWP025", image: "/assets/products/about_images.jpg", dimensions: "38*17*14 FT" },
      { sku: "CWP026", image: "/assets/products/about_images.jpg", dimensions: "36*15*14 FT" },
      { sku: "CWP027", image: "/assets/products/about_images.jpg", dimensions: "36*17*14 FT" },
      { sku: "CWP028", image: "/assets/products/about_images.jpg", dimensions: "27*18*15 FT" },
      { sku: "CWP029", image: "/assets/products/about_images.jpg", dimensions: "29*22*11 FT" },
      { sku: "CWP030", image: "/assets/products/about_images.jpg", dimensions: "31*16*10 FT" },
      { sku: "CWP031", image: "/assets/products/about_images.jpg", dimensions: "26*24*14 FT" },
      { sku: "CWP032", image: "/assets/products/about_images.jpg", dimensions: "27*17*11 FT" },
      { sku: "CWP033", image: "/assets/products/about_images.jpg", dimensions: "24*18*13 FT" },
      { sku: "CWP034", image: "/assets/products/about_images.jpg", dimensions: "28*28*11 FT" },
      { sku: "CWP035", image: "/assets/products/about_images.jpg", dimensions: "28*28*14 FT" },
      { sku: "CWP036", image: "/assets/products/about_images.jpg", dimensions: "25*22*12 FT" },
      { sku: "CWP037", image: "/assets/products/about_images.jpg", dimensions: "39*32*15 FT" },
      { sku: "CWP038", image: "/assets/products/about_images.jpg", dimensions: "37*22*16 FT" },
      { sku: "CWP039", image: "/assets/products/about_images.jpg", dimensions: "37*28*14 FT" },
      { sku: "CWP040", image: "/assets/products/about_images.jpg", dimensions: "36*18*16 FT" },
      { sku: "CWP041", image: "/assets/products/about_images.jpg", dimensions: "38*32*18 FT" },
    ]},
    { title: "Spring Rockers", items: [
      { sku: "CW0018", name: "Plain Spring Rocker", image: "/assets/products/about_images.jpg", dimensions: "29*13*30\"" },
      { sku: "CW0019", name: "Bike Spring Rocker", image: "/assets/products/about_images.jpg", dimensions: "35*10*34\"" },
      { sku: "CW0020", name: "Tortoise Spring Rocker", image: "/assets/products/about_images.jpg", dimensions: "25*16*31\"" },
      { sku: "CW0021", name: "Fish Spring Rocker", image: "/assets/products/about_images.jpg", dimensions: "25*16*30\"" },
      { sku: "CW0022", name: "Rabbit Spring Rocker", image: "/assets/products/about_images.jpg", dimensions: "26*16*30\"" },
      { sku: "CW0023", name: "Car Spring Rocker", image: "/assets/products/about_images.jpg", dimensions: "31*16*30\"" },
      { sku: "CW0024", name: "Dragon Spring Rocker", image: "/assets/products/about_images.jpg", dimensions: "27*16*30\"" },
      { sku: "CW0025", name: "Elephant Spring Rocker", image: "/assets/products/about_images.jpg", dimensions: "26*16*30\"" },
      { sku: "CW0032", name: "Horse Spring Rocker", image: "/assets/products/about_images.jpg", dimensions: "32*22*32\"" },
      { sku: "CW0033", name: "Elephant Spring Rocker", image: "/assets/products/about_images.jpg", dimensions: "31*17*30\"" },
      { sku: "CW0034", name: "Whale Spring Rocker", image: "/assets/products/about_images.jpg", dimensions: "33*17*37\"" },
      { sku: "CW0035", name: "Car Spring Rocker", image: "/assets/products/about_images.jpg", dimensions: "33*17*32\"" },
      { sku: "CW0036", name: "Dolphin Spring Rocker", image: "/assets/products/about_images.jpg", dimensions: "32*17*30\"" },
      { sku: "CW0037", name: "Frog Spring Rocker", image: "/assets/products/about_images.jpg", dimensions: "32*14*35\"" },
      { sku: "CW0038", name: "Bird Spring Rocker", image: "/assets/products/about_images.jpg", dimensions: "29*12*30\"" },
    ]},
    { title: "See Saw", items: [
      { sku: "CW0041", name: "Two Seater See-saw", image: "/assets/products/about_images.jpg", dimensions: "80*2*32\"" },
      { sku: "CW0040", name: "Four Seater See-saw Go Round", image: "/assets/products/about_images.jpg", dimensions: "136*20*32\"" },
    ]},
    { title: "Swings", items: [
      { sku: "CW0042", name: "Double Swing", image: "/assets/products/about_images.jpg", dimensions: "260*120*88\"" },
      { sku: "CW0043A", name: "Double Swing", image: "/assets/products/about_images.jpg", dimensions: "120*52*88\"" },
      { sku: "CW0043B", name: "Double Swing", image: "/assets/products/about_images.jpg", dimensions: "118*5*91\"" },
      { sku: "CW0043C", name: "Double Swing", image: "/assets/products/about_images.jpg", dimensions: "110*32*87\"" },
    ]},
  ],
  indoor: [
    { title: "Playstations", items: [
      { sku: "CW0027", image: "/assets/products/about_images.jpg", dimensions: "136*68*81\"" },
      { sku: "CW0028", image: "/assets/products/about_images.jpg", dimensions: "184*44*66\"" },
      { sku: "CW0029", image: "/assets/products/about_images.jpg", dimensions: "92*51*52\"" },
      { sku: "CW0030", image: "/assets/products/about_images.jpg", dimensions: "124*60*68\"" },
    ]},
    { title: "Rideons", items: [
      { sku: "CW2001", name: "Horse Rideon", image: "/assets/products/about_images.jpg", dimensions: "33*12*20\"" },
      { sku: "CW2002", name: "Duck Rideon", image: "/assets/products/about_images.jpg", dimensions: "33*12*20\"" },
      { sku: "CW2003", name: "Bunny Rideon", image: "/assets/products/about_images.jpg", dimensions: "33*12*20\"" },
      { sku: "CW2004", name: "Dolphin Rideon", image: "/assets/products/about_images.jpg", dimensions: "33*12*20\"" },
      { sku: "CW2005", name: "Hen Rideon", image: "/assets/products/about_images.jpg", dimensions: "33*12*20\"" },
      { sku: "CW2006", name: "Elephant Rideon", image: "/assets/products/about_images.jpg", dimensions: "33*12*20\"" },
      { sku: "CW2007", name: "Fox Rideon", image: "/assets/products/about_images.jpg", dimensions: "33*12*20\"" },
      { sku: "CW2008", name: "Sheep Rideon", image: "/assets/products/about_images.jpg", dimensions: "33*12*20\"" },
      { sku: "CW2009", name: "Donald Duck Rideon", image: "/assets/products/about_images.jpg", dimensions: "33*12*20\"" },
      { sku: "CW2010", name: "Whale Rideon", image: "/assets/products/about_images.jpg", dimensions: "44*20*17\"" },
      { sku: "CW2011", name: "Bear Rideon", image: "/assets/products/about_images.jpg", dimensions: "33*12*20\"" },
    ]},
    { title: "Tunnels", items: [
      { sku: "CW2012", name: "Frog Tunnel (4 sections/set)", image: "/assets/products/about_images.jpg" },
      { sku: "CW2013", name: "Caterpillar Tunnel (4 sections/set)", image: "/assets/products/about_images.jpg" },
    ]},
    { title: "Slides, Slides & Swing Combo", items: [
      { sku: "CW2017", name: "Elephant Slide", image: "/assets/products/about_images.jpg", dimensions: "67*35*43\"" },
      { sku: "CW2018", name: "Elephant Slide & Swing Combo", image: "/assets/products/about_images.jpg", dimensions: "64*68*46\"" },
      { sku: "CW2019", name: "Bear Slide", image: "/assets/products/about_images.jpg", dimensions: "67*35*46\"" },
      { sku: "CW2020", name: "Bear Slide & Swing Combo", image: "/assets/products/about_images.jpg", dimensions: "64*68*46\"" },
      { sku: "CW2021", name: "Euro Slide", image: "/assets/products/about_images.jpg", dimensions: "64*35*43\"" },
      { sku: "CW2022", name: "Euro Slide & Swing Combo", image: "/assets/products/about_images.jpg", dimensions: "64*68*50\"" },
      { sku: "CW2023", name: "Giraffe Slide", image: "/assets/products/about_images.jpg", dimensions: "67*35*45\"" },
      { sku: "CW2024", name: "Giraffe Slide & Swing Combo", image: "/assets/products/about_images.jpg", dimensions: "64*68*46\"" },
      { sku: "CW2025", name: "Super Senior Slide", image: "/assets/products/about_images.jpg", dimensions: "64*35*43\"" },
      { sku: "CW2026", name: "Super Senior Slide & Swing Combo", image: "/assets/products/about_images.jpg", dimensions: "64*68*50\"" },
      { sku: "CW2027", name: "Super Senior Swing", image: "/assets/products/about_images.jpg", dimensions: "36*20*28\"" },
      { sku: "CW2028", name: "Junior Slide", image: "/assets/products/about_images.jpg", dimensions: "44*20*28\"" },
    ]},
    { title: "Floorings", items: [
      { sku: "CW2042", name: "Alphabet Eva Mat", image: "/assets/products/about_images.jpg", dimensions: "1*1 FT" },
      { sku: "CW2044", name: "Eva Mat", image: "/assets/products/about_images.jpg", dimensions: "2*2 FT" },
      { sku: "CW2045", name: "Eva Mat", image: "/assets/products/about_images.jpg", dimensions: "1*1 MTR" },
      { sku: "CW2046", name: "Number Eva Mat", image: "/assets/products/about_images.jpg", dimensions: "1*1 FT" },
      { sku: "CW2067", name: "Artificial Grass", image: "/assets/products/about_images.jpg", dimensions: "25mm, 35mm, 45mm" },
    ]},
  ],
};