export const PRODUCT_CATALOG = {
  indoorDigitalSignage: {
    floorStanding: {
      features: [
        { title: "Perfect Image", description: "High brightness, High contrast ratio, high resolution support full HD 1920*1080", image: "/assets/products/indoor-lcd-ad-player-1-300x111.jpg" },
        { title: "Easy Operation", description: "Stand-alone Version: USB or SD drive. Network version: one control terminal can control lots of players via network.", image: "/assets/products/indoor-lcd-ad-player-2-300x111.jpg" },
        { title: "Smart Schedule", description: "Default video play setting date, time video/pictures expired video auto delete cut-in video", image: "/assets/products/indoor-lcd-ad-player-3-300x111.jpg" },
        { title: "Safe", description: "Stand-alone Version: adding protection lock avoid strangers to change storage media", image: "/assets/products/indoor-lcd-ad-player-4-300x111.jpg" },
        { title: "Fashion Design", description: "Modern and sleek design, it can combine with environment. Vandal proof, antiglare and other functions customizable.", image: "/assets/products/indoor-lcd-ad-player-5-300x111.jpg" },
        { title: "Video Encryption", description: "Video list videos set verification. It can only upload verified videos.", image: "/assets/products/indoor-lcd-ad-player-6-300x111.jpg" },
        { title: "Screen Splitting", description: "Support horizontal screen, vertical screen full screen and splitting mode it can support rolling subtitle.", image: "/assets/products/indoor-lcd-ad-player-7-300x111.jpg" },
        { title: "Display Mode", description: "Support video, flash, picture, word mixed play. 20 kinds of PPT switch modes.", image: "/assets/products/indoor-lcd-ad-player-8-300x111.jpg" },
      ],
      specs: {
        title: "Floor Standing Series - Round Corner (R)",
        subtitle: "Available in 42\" / 46\" / 55\" / 65\"",
        columns: [
          { key: "model", label: "Model" },
          { key: "size", label: "Size" },
          { key: "resolution", label: "Resolution" },
          { key: "brightness", label: "Brightness (nits)" },
          { key: "contrast", label: "Contrast Ratio" },
          { key: "viewing", label: "Viewing Angle" },
          { key: "response", label: "Response Time" },
          { key: "lifetime", label: "Lifetime" },
          { key: "consumption", label: "Consumption" },
          { key: "dimension", label: "Dimension (mm)" },
        ],
        rows: [
          { model: "GS-AD42FS-R", size: "42\"", resolution: "1080x1920", brightness: "400", contrast: "4000:1", viewing: "175\u00b0", response: "6ms", lifetime: "60000 hrs", consumption: "80W", dimension: "1789x635x453" },
          { model: "GS-AD46FS-R", size: "46\"", resolution: "1080x1920", brightness: "450", contrast: "4000:1", viewing: "175\u00b0", response: "6ms", lifetime: "60000 hrs", consumption: "120W", dimension: "1850x690x423" },
          { model: "GS-AD55FS-R", size: "55\"", resolution: "1080x1920", brightness: "450", contrast: "3000:1", viewing: "175\u00b0", response: "6ms", lifetime: "60000 hrs", consumption: "160W", dimension: "1925x796x492" },
          { model: "GS-AD65FS-R", size: "65\"", resolution: "1080x1920", brightness: "500", contrast: "3000:1", viewing: "175\u00b0", response: "6ms", lifetime: "60000 hrs", consumption: "350W", dimension: "2123x937x620" },
        ],
      },
    },
    wallMounting: {
      features: [
        { title: "Perfect Image", description: "High brightness, High contrast ratio, high resolution support full HD 1920*1080", image: "/assets/products/indoor-lcd-ad-player-1-300x111.jpg" },
        { title: "Easy Operation", description: "Stand-alone Version: USB or SD drive. Network version: one control terminal can control lots of players via network.", image: "/assets/products/indoor-lcd-ad-player-2-300x111.jpg" },
        { title: "Smart Schedule", description: "Default video play setting date, time video/pictures expired video auto delete cut-in video", image: "/assets/products/indoor-lcd-ad-player-3-300x111.jpg" },
        { title: "Safe", description: "Stand-alone Version: adding protection lock avoid strangers to change storage media", image: "/assets/products/indoor-lcd-ad-player-4-300x111.jpg" },
        { title: "Fashion Design", description: "Modern and sleek design, it can combine with environment. Vandal proof, antiglare and other functions customizable.", image: "/assets/products/indoor-lcd-ad-player-5-300x111.jpg" },
        { title: "Video Encryption", description: "Video list videos set verification. It can only upload verified videos.", image: "/assets/products/indoor-lcd-ad-player-6-300x111.jpg" },
        { title: "Screen Splitting", description: "Support horizontal screen, vertical screen full screen and splitting mode it can support rolling subtitle.", image: "/assets/products/indoor-lcd-ad-player-7-300x111.jpg" },
        { title: "Display Mode", description: "Support video, flash, picture, word mixed play. 20 kinds of PPT switch modes.", image: "/assets/products/indoor-lcd-ad-player-8-300x111.jpg" },
      ],
      specs: {
        title: "Wall Mounted Indoor LCD AD Player",
        subtitle: "Available in 22\" / 32\" / 42\" / 46\" / 55\" / 65\" / 70\"",
        columns: [
          { key: "model", label: "Model" },
          { key: "size", label: "Size" },
          { key: "resolution", label: "Resolution" },
          { key: "brightness", label: "Brightness (nits)" },
          { key: "contrast", label: "Contrast Ratio" },
          { key: "consumption", label: "Consumption" },
          { key: "dimension", label: "Dimension (mm)" },
          { key: "version", label: "Version" },
        ],
        rows: [
          { model: "GS-AD22WM", size: "22\"", resolution: "1920x1080", brightness: "250", contrast: "3000:1", consumption: "32W", dimension: "558x280x37", version: "Network" },
          { model: "GS-AD32WM", size: "32\"", resolution: "1366x768", brightness: "400", contrast: "4000:1", consumption: "65W", dimension: "791x489x54", version: "Network" },
          { model: "GS-AD42WM", size: "42\"", resolution: "1920x1080", brightness: "400", contrast: "4000:1", consumption: "80W", dimension: "1030x623x51", version: "Network" },
          { model: "GS-AD46WM", size: "46\"", resolution: "1920x1080", brightness: "400", contrast: "4000:1", consumption: "120W", dimension: "1158x722x74", version: "Network" },
          { model: "GS-AD55WM", size: "55\"", resolution: "1920x1080", brightness: "500", contrast: "5000:1", consumption: "160W", dimension: "1378x838x69", version: "Network" },
          { model: "GS-AD65WM", size: "65\"", resolution: "1920x1080", brightness: "500", contrast: "5000:1", consumption: "200W", dimension: "1601x972x79", version: "Network" },
          { model: "GS-AD70WM", size: "70\"", resolution: "1920x1080", brightness: "400", contrast: "4000:1", consumption: "240W", dimension: "1673x996x103", version: "Network" },
        ],
      },
    },
  },
  smartTouchTable: {
    introduction: "Multi-touch tables may be next step when it comes to interactions between man and machine. Though actually their use doesn't target the general public, Multi-touch tables are already popular in the professional environment. Touch tables are sophisticated devices that enable advanced and intelligent interaction between human and machine.",
    howItWorks: [
      { title: "Diffused Illumination (DI)", description: "This technology uses multiple infrared illuminators placed under the screen. Once the user touches the surface of the table, this shall reflect the light emitted by the point of contact to an infrared camera facing the screen. All movements made by the user are detected and then interpreted by the software embedded in the table." },
      { title: "Frustrated Total Internal Reflection (FTIR)", description: "Infrared emitting diodes are placed along the edges of a sheet of glass. With this system, infrared radiation beam is actually confined only inside the glass plate. Since light cannot escape, it is reflected and bounces across the surface. Thus, when the user touches the table, the light emitted by LEDs is redirected to a camera." },
    ],
    whyUse: "Beyond the technological leap that touch table represents, they can become a real value to a professional. You will be able to offer customers a simple, practical and interactive vision of your product or service. For example, when making a purchase, in addition to the advice you can give, you can talk around the table while making demonstrations.",
    keyFeatures: [
      "Large screens (30 inches) and very good graphics resolutions",
      "Internet connection (Ethernet, WiFi)",
      "Audio outputs",
      "Detection and interaction with objects",
      "A 2D and 3D design",
      "Multi user and multi touch applications",
      "Software tailored to the professional activities",
    ],
    specs: {
      title: "Smart Touch Table Specifications",
      columns: [
        { key: "model", label: "Model" },
        { key: "size", label: "Size" },
        { key: "description", label: "Description" },
      ],
      rows: [
        { model: "GS-TT-32", size: "32\"", description: "20 Points Foil Touch Table 32\" IR Touch / 400cd m brightness / acrylic design. PC: Intel Core i3/i5/i7, RAM 4-16GB, HDD 160-500GB, Win 7/10" },
        { model: "GS-TT-42", size: "42\"", description: "20 Points Foil Touch Table 42\" IR Touch / 400cd m brightness / acrylic design. PC: Intel Core i3/i5/i7, RAM 4-16GB, HDD 160-500GB, Win 7/10" },
        { model: "GS-TT-46", size: "46\"", description: "20 Points Foil Touch Table 46\" IR Touch / 400cd m brightness. PC: Intel Core i3/i5/i7, RAM 4-16GB, HDD 160-500GB, Win 7/10" },
      ],
    },
    variant21: {
      title: "Smart Touch Table - 21.5 Inches",
      features: [
        "Toughened glass, Aluminium frame, stainless Steel, Aeronautical Design Power Port",
        "Water Proof IP 43 Rating",
        "Capacitive 10 Point Touch",
        "Powered with Android Quad core powered with 2GB Ram, with full HD",
        "2 mobile phone charging ports",
      ],
      applications: ["Restaurant Tables", "Coffee Shops", "Retail Shops", "Customer Interaction Table"],
    },
  },
  wayfindingKiosk: {
    features: [
      { title: "Interactive Map", description: "Interactive wayfinding comes with intuitive interface that makes it much easier for visitor to read & understand map. The block based 2D map has multiple colours which can be used for colour coding in map too." },
      { title: "Directory Listing", description: "Along with map, interactive wayfinding can provide directory view of the elements in map. For e.g. in mall all the shops can be categorised in their respective genre like fashion, electronics etc. Visitor can browse through all the shops listed and find the desired shop and find the shortest possible path for the same." },
      { title: "Less Time & More Productivity", description: "Since the visitor can find any destination with shortest possible route, it saves lot of time on the part of customer. If in a mall, Mr. A want to go to a particular shop he can just search in interactive wayfinding directory and find the route easily." },
      { title: "Attractive Branding Option", description: "Interactive wayfinding for huge premises with multiple options is necessity but it also provides option for effective branding. When the wayfinder is idle, different type of logo animation, videos or images can be shown." },
    ],
    applications: [
      { title: "Retail", description: "Mall is large premises & many times visitors find it tough to find the desired store or restaurant. Interactive wayfinding is perfect solution where visitor can choose from the directory or just tap on the desired store and find shortest route available." },
      { title: "Healthcare", description: "Hospital premises are large in nature with multiple facilities & departments. It is often confusing for a patient or visitor; in such case, interactive wayfinding with touch kiosk can provide details along with map of the premises." },
      { title: "Airport", description: "Each airport has multiple terminals, each terminal has multiple check-in counters, gates etc. For passengers, interactive wayfinding can be very helpful to get around and board the flight on time." },
      { title: "Corporate", description: "Big corporate campus & centres, host either many offices or multiple divisions. Offices often include visitors; interactive wayfinding can serve the visitors very well to guide them and it will also go with the sophisticated decor." },
      { title: "Events", description: "Large events and conferences benefit from wayfinding kiosks to guide attendees between sessions, exhibition halls, and facilities." },
      { title: "Museums", description: "Museums use interactive wayfinding to help visitors navigate exhibits, find specific collections, and access multimedia guides." },
      { title: "Hospitality", description: "Hotels and resorts deploy wayfinding solutions to help guests navigate lobbies, conference areas, restaurants, and recreational facilities." },
    ],
    caseStudy: {
      title: "Interactive Wayfinding Solution",
      client: "Phoenix Mills - Phoenix Marketcity",
      description: "Phoenix Mills run chain of malls in major cities of India, these malls all over the cities host huge number of footfalls. To set up a better guidance system Xtreme Media have provided interactive wayfinding solution which provides directory of all the shops & amenities on the premises. This solution offers search option along with shortest route available. This is a unique combination of hardware & software that help mall management to create visiting mall a hassle free experience.",
      deployments: [
        { location: "Mumbai - Phoenix Marketcity Kurla", details: "9 Kiosks deployed" },
        { location: "Mumbai - High Street Phoenix Lower Parel", details: "4 Kiosks deployed" },
        { location: "Pune - Phoenix Marketcity Vimannagar", details: "6 Kiosks deployed" },
        { location: "Bangalore - Phoenix Marketcity", details: "8 Kiosks deployed" },
      ],
    },
  },
  touchScreenKiosk: {
    mainFeatures: [
      "Adopt high quality IR touch, Resistance touch, Capacitive touch, high transparency, strong capability against force rub-proof and scrape-proof and water proof.",
      "High sensitivity touch function, fast response, no image drifting.",
      "Industry LED panel, HD image, High brightness and good operation stability.",
      "Outstanding enclosure design, beautiful ultra-thin outlook, with excellent protection grade and prevent electromagnetism disturb performance.",
      "Adopt industrial mother board and famous brand devices, combine with Windows, Android, support 4-10 dots touch.",
      "High reliability, high stability, apply to education, training, exhibition display, public media, video meeting, military command, transportation management.",
    ],
    lcdSpecs: {
      title: "LCD Panel Specification",
      columns: [
        { key: "param", label: "Parameter" },
        { key: "gs-tk19", label: "GS-TK19 (19\")" },
        { key: "gs-tk22", label: "GS-TK22 (22\")" },
        { key: "gs-tk32", label: "GS-TK32 (32\")" },
        { key: "gs-tk42", label: "GS-TK42 (42\")" },
        { key: "gs-tk46", label: "GS-TK46 (46\")" },
        { key: "gs-tk55", label: "GS-TK55 (55\")" },
      ],
      rows: [
        { param: "Size", "gs-tk19": "19\"", "gs-tk22": "22\"", "gs-tk32": "32\"", "gs-tk42": "42\"", "gs-tk46": "46\"", "gs-tk55": "55\"" },
        { param: "Resolution", "gs-tk19": "1280x1024", "gs-tk22": "1680x1050", "gs-tk32": "1366x768", "gs-tk42": "1920x1080", "gs-tk46": "1920x1080", "gs-tk55": "1920x1080" },
        { param: "Brightness (nits)", "gs-tk19": "350", "gs-tk22": "250", "gs-tk32": "450", "gs-tk42": "450", "gs-tk46": "400", "gs-tk55": "450" },
        { param: "Color", "gs-tk19": "16.7M", "gs-tk22": "16.7M", "gs-tk32": "16.7M", "gs-tk42": "16.7M", "gs-tk46": "16.7M", "gs-tk55": "16.7M" },
        { param: "Viewing Angle", "gs-tk19": "170\u00b0/170\u00b0", "gs-tk22": "170\u00b0/170\u00b0", "gs-tk32": "170\u00b0/170\u00b0", "gs-tk42": "170\u00b0/170\u00b0", "gs-tk46": "170\u00b0/170\u00b0", "gs-tk55": "170\u00b0/170\u00b0" },
        { param: "Contrast Ratio", "gs-tk19": "1000:1", "gs-tk22": "1000:1", "gs-tk32": "1000:1", "gs-tk42": "1000:1", "gs-tk46": "1000:1", "gs-tk55": "1000:1" },
        { param: "Response Time", "gs-tk19": "4ms", "gs-tk22": "4ms", "gs-tk32": "4ms", "gs-tk42": "4ms", "gs-tk46": "4ms", "gs-tk55": "4ms" },
        { param: "Lifetime", "gs-tk19": "\u226560000 hrs", "gs-tk22": "\u226560000 hrs", "gs-tk32": "\u226560000 hrs", "gs-tk42": "\u226560000 hrs", "gs-tk46": "\u226560000 hrs", "gs-tk55": "\u226560000 hrs" },
      ],
    },
    touchSpecs: {
      title: "Touch Panel Specification",
      columns: [
        { key: "param", label: "Parameter" },
        { key: "value", label: "Specification" },
      ],
      rows: [
        { param: "Touch Way", value: "Infrared touch / Capacitive touch" },
        { param: "Location Accuracy", value: "\u00b1 2mm" },
        { param: "Light Transmittance", value: "\u2265 92%" },
        { param: "Hardness", value: "7H" },
        { param: "Response Time", value: "\u2264 10ms" },
        { param: "Output Resolution", value: "4096 x 4096" },
      ],
    },
    pcSpecs: {
      title: "PC Configuration",
      columns: [
        { key: "config", label: "Configuration" },
        { key: "details", label: "Details" },
      ],
      rows: [
        { config: "Standard", details: "Main board-H61, CPU: i3 3220, RAM: 4G, Hard disk: 500G" },
        { config: "Medium", details: "Main board-H61, CPU: i5, RAM: 4G, Hard disk: 500G" },
        { config: "High", details: "Main board-H61, CPU: i7, RAM: 4G, Hard disk: 500G" },
      ],
    },
    powerSpecs: {
      title: "Power Specification",
      columns: [
        { key: "param", label: "Parameter" },
        { key: "gs-tk19", label: "GS-TK19" },
        { key: "gs-tk22", label: "GS-TK22" },
        { key: "gs-tk32", label: "GS-TK32" },
        { key: "gs-tk42", label: "GS-TK42" },
        { key: "gs-tk46", label: "GS-TK46" },
        { key: "gs-tk55", label: "GS-TK55" },
      ],
      rows: [
        { param: "Consumption", "gs-tk19": "180W", "gs-tk22": "260W", "gs-tk32": "300W", "gs-tk42": "", "gs-tk46": "", "gs-tk55": "650W" },
      ],
    },
    environment: {
      title: "Operating Environment",
      columns: [
        { key: "param", label: "Parameter" },
        { key: "value", label: "Specification" },
      ],
      rows: [
        { param: "Operating Temperature", value: "0-50\u00b0C" },
        { param: "Operating Humidity", value: "20%-80%" },
        { param: "Storage Temperature", value: "-10\u00b0C to 60\u00b0C" },
        { param: "Storage Humidity", value: "5%-95%" },
      ],
    },
    case: {
      title: "Case Specification",
      columns: [
        { key: "param", label: "Parameter" },
        { key: "value", label: "Specification" },
      ],
      rows: [
        { param: "Material", value: "Cold-rolled steel SPCC / Aluminum panel / Customizable" },
        { param: "Color", value: "Black / White or others" },
        { param: "Dimension", value: "Customizable" },
        { param: "Base", value: "Base support included" },
      ],
    },
  },
  videoWall: {
    description: "Godspeed LCD video wall adopted original A+ LCD Panel from SAMSUNG, LG, which brings you perfect visual experience. Our high quality products and customized solutions are widely applied in Security system, Shopping mall, Hotel, Exhibition center, Bank around the world. We keep pace with the latest ultra thin splicing technology, combined with intelligent and easy-operation video wall controlling system.",
    specs: {
      title: "Video Wall Models",
      subtitle: "Available in 42\" / 46\" / 55\"",
      columns: [
        { key: "model", label: "Model" },
        { key: "brightness", label: "Brightness (nits)" },
        { key: "consumption", label: "Consumption" },
        { key: "contrast", label: "Contrast Ratio" },
        { key: "gap", label: "Gap (mm)" },
      ],
      rows: [
        { model: "GS-VW4667L", brightness: "450", consumption: "200W", contrast: "3500:1", gap: "6.7mm" },
        { model: "GS-VW4667H", brightness: "700", consumption: "280W", contrast: "3000:1", gap: "6.7mm" },
        { model: "GS-VW4653L", brightness: "450", consumption: "150W", contrast: "3500:1", gap: "5.3mm" },
        { model: "GS-VW4653H", brightness: "700", consumption: "170W", contrast: "5000:1", gap: "5.3mm" },
        { model: "GS-VW4610L", brightness: "500", consumption: "130W", contrast: "3000:1", gap: "10mm" },
        { model: "GS-VW4635H", brightness: "700", consumption: "200W", contrast: "3000:1", gap: "3.5mm" },
      ],
    },
    common: {
      title: "Common Specifications",
      columns: [
        { key: "param", label: "Parameter" },
        { key: "value", label: "Value" },
      ],
      rows: [
        { param: "Display Ratio", value: "16:9" },
        { param: "Resolution", value: "1920 x 1080" },
        { param: "Color", value: "16.7M" },
        { param: "Viewing Angle", value: "Horizontal: 178\u00b0; Vertical: 178\u00b0" },
        { param: "Response Time", value: "6ms" },
      ],
    },
  },
  tellus: {
    whyFeedback: "The purpose of business can be measured only with the Customer/Guest feedback i.e Restaurant/retail outlets should meet the purpose of customer walk in, how the staff handle the customer? If the purpose - Food the guest want to eat / Grocery he want to buy from your supermarket... if the customer is not comfortable he may go to your competitors or he may give a poor review to his friends and social media.",
    whyTellUs: "Why Tell Us? It will send the Text to the concern brand owner INSTANTLY about the guest comment for poor rating with customer name and mobile number.",
    features: [
      "All feedback collected electronically",
      "Customize your own questions",
      "Download Feedback in excel and can do analyses",
      "No Big investment - Each branch feedback collect @ less than Rs 20 per day (Cost of one Water bottle)",
      "Instant Alert for negative feedbacks to owners by SMS",
      "Portal access option for Chain of outlets",
      "Tell Us will improve your customer service approach",
      "Easy to measure Which staff is better in which branch",
      "Product quality and consistency can be maintained",
      "Increase repeat customers and increase PROFIT",
      "Help you to get all potential customer data, you can send personalised messages to dis-satisfied customer and offer Gift coupons to loyal customers",
    ],
    hardware: [
      { name: "Stainless Steel Floor Standing Feedback Kiosk", image: "/assets/products/X11C1367-200x300.jpg" },
      { name: "10 Inch Tablet", image: "/assets/products/X11C1380-200x300.jpg" },
      { name: "7 Inch Tablet", image: "/assets/products/X11C1375-200x300.jpg" },
    ],
  },
  hardware: {
    items: [
      { name: "Server (HP ML10)", image: "/assets/products/H1-300x206.jpg" },
      { name: "PC (DELL)", image: "/assets/products/d1.jpg" },
      { name: "Posiflex: 3316E", image: "/assets/products/d3.jpg" },
      { name: "Partnertech - SP850", image: "/assets/products/d4.jpg" },
      { name: "Epson POS / KOT Printers", image: "/assets/products/d5.jpg" },
      { name: "Model: TM-T82 II, M30", image: "/assets/products/d5-1.jpg" },
      { name: "Cash Drawers", image: "/assets/products/d7.jpg" },
      { name: "Thermal Rolls For Billing", image: "/assets/products/79mm-1.jpg" },
      { name: "7 inch TAB for KOT", image: "/assets/products/tab.jpg" },
    ],
  },
};